import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Inter } from "next/font/google"
import { Providers } from "./providers"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter" // Add a CSS variable for the font
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-background text-foreground`}>
        <Providers>
          <Navbar />
          <main className="mx-auto pt-20">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
